language: python
python:
  - "3.2"
  - "3.3"
# install dependencies
before_install:
  - git clone git://github.com/libgit2/libgit2.git -b master
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
install: "pip install -r requirements.txt --use-mirrors"
# run tests
script: "echo"
