language: python
python:
  - "3.2"
  - "3.3"
# install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgit2-dev
install: "pip install -r requirements.txt --use-mirrors"
# run tests
script: "echo"
