language: python
python:
  - 3.2
  - 3.3
before_install:
  - git clone git://github.com/libgit2/libgit2.git -b master
  - cd libgit2 && mkdir build && cd build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
  - cd ../..
install: 
  - pip install -r requirements-testing.txt --use-mirrors
  - pip install coveralls
  - python setup.py install
script:
  - nosetests --with-coverage --cover-package=sundara
after_success:
  - coveralls

