language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - git clone git://github.com/libgit2/libgit2.git -b master
  - cd libgit2 && mkdir build && cd build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
  - cd ../..
install: pip install -r requirements.txt --use-mirrors
script: nosetests --with-coverage --cover-package=sundara
