language: python
python:
  - 3.2
  - 3.3
  - 3.4
before_install:
  - wget https://github.com/libgit2/libgit2/archive/v0.20.0.tar.gz
  - tar xf v0.20.0.tar.gz
  - cd libgit2-0.20.0 && mkdir build && cd build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
  - cd ../..
install:
  - export LIBGIT2="/usr/local"
  - export LDFLAGS="-Wl,-rpath='$LIBGIT2/lib',--enable-new-dtags $LDFLAGS"
  - export CFLAGS="-Wno-error=declaration-after-statement"
  - pip install pygit2
  - unset LDFLAGS
  - unset CFLAGS
  - pip install -r tests/requirements.txt --use-mirrors
  - pip install coveralls
  - python setup.py install
script:
  - nosetests --with-coverage --cover-package=sundara
after_success:
  - coveralls

